baseURL = 'distracted-ptolemy-fab21c.netlify.app'
languageCode = 'en-us'
title = 'LIMSABC | When you need results'

[Params]
  phone = '1-800-834-8618'
  linkedin='/'
  twitter='/'

[menu]

[[menu.nav]]
  identifier = 'home'
  name = 'HOME'
  title = 'HOME'
  pageref = '/'
  weight = 1


[[menu.nav]]
  identifier = 'SOLUTIONS'
  name = 'SOLUTIONS'
  title = 'SOLUTIONS'
  pageref = '/s'
  weight = 2

[[menu.nav]]
  identifier = 'PATIENT PORTAL'
  name = 'PATIENT PORTAL'
  title = 'PATIENT PORTAL'
  pageref = '/s'
  weight = 3

[[menu.nav]]
  identifier = 'PRICING'
  name = 'PRICING'
  title = 'PRICING'
  pageref = '/s'
  weight = 4

[[menu.nav]]
  identifier = 'PLATFORM'
  name = 'PLATFORM'
  title = 'PLATFORM'
  pageref = '/s'
  weight = 5

[[menu.nav]]
  identifier = 'NEWSROOM'
  name = 'NEWSROOMs'
  title = 'NEWSROOM'
  pageref = '/s'
  weight = 6

[[menu.nav]]
  identifier = 'blog'
  name = 'BLOG'
  title = 'BLOG'
  pageref = '/blog/'
  weight = 7

[[menu.nav]]
  identifier = 'CONTACT'
  name = 'CONTACT'
  title = 'CONTACT'
  pageref = '/s'
  weight = 8

[[menu.nav]]
  identifier = 'DEMO'
  name = 'DEMO'
  title = 'DEMO'
  pageref = '/s'
  weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

paginate = 2